/* Updated schema for API‑only book data */
-- Create profiles table
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    user_id TEXT NOT NULL CHECK (
        user_id = lower(user_id)
        AND user_id ~ '^[a-z0-9_]{3,20}$'
    ),
    avatar_url TEXT,
    bio TEXT,
    followers_count INTEGER DEFAULT 0,
    following_count INTEGER DEFAULT 0,
    read_count INTEGER DEFAULT 0,
    is_private BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE UNIQUE INDEX IF NOT EXISTS profiles_user_id_lower_unique
    ON public.profiles (lower(user_id));

-- Legal name, date of birth and phone number must never be publicly readable.
CREATE TABLE IF NOT EXISTS public.account_details (
    profile_id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
    full_name TEXT NOT NULL CHECK (char_length(btrim(full_name)) BETWEEN 1 AND 100),
    birth_date DATE NOT NULL CHECK (
        birth_date >= DATE '1900-01-01'
        AND birth_date <= CURRENT_DATE
    ),
    phone_number TEXT NOT NULL CHECK (phone_number ~ '^\+?[0-9]{7,15}$'),
    phone_verified_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.account_details ENABLE ROW LEVEL SECURITY;

-- NOTE: books table removed; external API provides book data.

-- Posts now reference external book IDs (ISBN or other) as plain TEXT
CREATE TABLE IF NOT EXISTS public.posts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    book_id TEXT NOT NULL,
    rating DOUBLE PRECISION NOT NULL CHECK (rating >= 1.0 AND rating <= 5.0),
    comment TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;

-- Favorites reference external book IDs as TEXT
CREATE TABLE IF NOT EXISTS public.favorites (
    profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    book_id TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (profile_id, book_id)
);

ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;

-- Collections track reading status for external book IDs as TEXT
CREATE TABLE IF NOT EXISTS public.collections (
    profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    book_id TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('to_read', 'reading', 'read')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (profile_id, book_id)
);

ALTER TABLE public.collections ENABLE ROW LEVEL SECURITY;

-- Legal consent history for the exact document bundle accepted by a user.
CREATE TABLE IF NOT EXISTS public.legal_consents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    bundle_version TEXT NOT NULL,
    terms_version TEXT NOT NULL,
    privacy_version TEXT NOT NULL,
    community_guidelines_version TEXT NOT NULL,
    infringement_policy_version TEXT NOT NULL,
    external_transmission_version TEXT NOT NULL,
    auth_provider TEXT,
    accepted_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE (profile_id, bundle_version)
);

ALTER TABLE public.legal_consents ENABLE ROW LEVEL SECURITY;

-- Contact requests are write-only from the public app and readable in the
-- Supabase Dashboard by the operator.
CREATE TABLE IF NOT EXISTS public.contact_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    email TEXT NOT NULL CHECK (char_length(email) BETWEEN 3 AND 320),
    category TEXT NOT NULL CHECK (
        category IN ('general', 'privacy', 'infringement', 'report', 'account', 'other')
    ),
    subject TEXT NOT NULL CHECK (char_length(subject) BETWEEN 1 AND 120),
    message TEXT NOT NULL CHECK (char_length(message) BETWEEN 1 AND 4000),
    status TEXT NOT NULL DEFAULT 'received' CHECK (status IN ('received', 'in_progress', 'closed')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.contact_requests ENABLE ROW LEVEL SECURITY;

-- RLS Policies (same as before)
CREATE POLICY "Allow public read access for profiles" ON public.profiles
    FOR SELECT USING (true);

CREATE POLICY "Allow users to update their own profile" ON public.profiles
    FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Allow users to insert their own profile" ON public.profiles
    FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can read their own account details" ON public.account_details
    FOR SELECT TO authenticated USING (auth.uid() = profile_id);

CREATE POLICY "Users can insert their own account details" ON public.account_details
    FOR INSERT TO authenticated WITH CHECK (auth.uid() = profile_id);

CREATE POLICY "Users can update their own account details" ON public.account_details
    FOR UPDATE TO authenticated
    USING (auth.uid() = profile_id)
    WITH CHECK (auth.uid() = profile_id);

CREATE POLICY "Allow visible profile posts to be read" ON public.posts
    FOR SELECT USING (
        auth.uid() = profile_id
        OR EXISTS (
            SELECT 1
            FROM public.profiles AS profile
            WHERE profile.id = posts.profile_id
              AND profile.is_private = false
        )
    );

CREATE POLICY "Allow authenticated users to insert posts" ON public.posts
    FOR INSERT WITH CHECK (auth.uid() = profile_id);

CREATE POLICY "Allow visible profile favorites to be read" ON public.favorites
    FOR SELECT USING (
        auth.uid() = profile_id
        OR EXISTS (
            SELECT 1
            FROM public.profiles AS profile
            WHERE profile.id = favorites.profile_id
              AND profile.is_private = false
        )
    );

CREATE POLICY "Allow authenticated users to insert/delete favorites" ON public.favorites
    FOR ALL USING (auth.uid() = profile_id);

CREATE POLICY "Allow visible profile collections to be read" ON public.collections
    FOR SELECT USING (
        auth.uid() = profile_id
        OR EXISTS (
            SELECT 1
            FROM public.profiles AS profile
            WHERE profile.id = collections.profile_id
              AND profile.is_private = false
        )
    );

CREATE POLICY "Allow authenticated users to insert/delete collections" ON public.collections
    FOR ALL USING (auth.uid() = profile_id);

CREATE POLICY "Users can read their own legal consents" ON public.legal_consents
    FOR SELECT USING (auth.uid() = profile_id);

CREATE POLICY "Users can insert their own legal consents" ON public.legal_consents
    FOR INSERT WITH CHECK (auth.uid() = profile_id);

CREATE POLICY "Anyone can submit a contact request" ON public.contact_requests
    FOR INSERT TO anon, authenticated
    WITH CHECK (
        status = 'received'
        AND (profile_id IS NULL OR auth.uid() = profile_id)
    );

GRANT SELECT, INSERT ON public.legal_consents TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.legal_consents_id_seq TO authenticated;
GRANT INSERT ON public.contact_requests TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.contact_requests_id_seq TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.account_details TO authenticated;

CREATE OR REPLACE FUNCTION public.complete_registration(
    p_full_name TEXT,
    p_birth_date DATE,
    p_phone_number TEXT,
    p_username TEXT,
    p_user_id TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
    current_profile_id UUID := auth.uid();
    normalized_user_id TEXT := lower(btrim(p_user_id));
    normalized_phone TEXT := regexp_replace(p_phone_number, '[^0-9+]', '', 'g');
BEGIN
    IF current_profile_id IS NULL THEN
        RAISE EXCEPTION 'Authentication required' USING ERRCODE = '42501';
    END IF;

    IF char_length(btrim(p_full_name)) NOT BETWEEN 1 AND 100
        OR p_birth_date < DATE '1900-01-01'
        OR p_birth_date > CURRENT_DATE
        OR normalized_phone !~ '^\+?[0-9]{7,15}$'
        OR char_length(btrim(p_username)) NOT BETWEEN 1 AND 30
        OR normalized_user_id !~ '^[a-z0-9_]{3,20}$'
    THEN
        RAISE EXCEPTION 'Invalid registration data' USING ERRCODE = '23514';
    END IF;

    IF normalized_user_id IN (
        'admin', 'administrator', 'support', 'sharemarium', 'system', 'official'
    ) THEN
        RAISE EXCEPTION 'Reserved user ID' USING ERRCODE = '23514';
    END IF;

    UPDATE public.profiles
    SET username = btrim(p_username), user_id = normalized_user_id
    WHERE id = current_profile_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Profile not found' USING ERRCODE = 'P0002';
    END IF;

    INSERT INTO public.account_details (
        profile_id, full_name, birth_date, phone_number
    ) VALUES (
        current_profile_id, btrim(p_full_name), p_birth_date, normalized_phone
    )
    ON CONFLICT (profile_id) DO UPDATE
    SET full_name = EXCLUDED.full_name,
        birth_date = EXCLUDED.birth_date,
        phone_number = EXCLUDED.phone_number,
        phone_verified_at = CASE
            WHEN public.account_details.phone_number = EXCLUDED.phone_number
                THEN public.account_details.phone_verified_at
            ELSE NULL
        END,
        updated_at = timezone('utc'::text, now());
END;
$$;

REVOKE ALL ON FUNCTION public.complete_registration(TEXT, DATE, TEXT, TEXT, TEXT)
    FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.complete_registration(TEXT, DATE, TEXT, TEXT, TEXT)
    TO authenticated;

-- Seed data now only includes profiles (books are fetched from external APIs)
INSERT INTO public.profiles (id, username, user_id, avatar_url, bio, followers_count, following_count, read_count)
VALUES
    ('d3b07384-d113-4ec5-a587-f3e098a58f4a', 'ryu_booklover', 'ryu_booklover', 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80', '本を読むのが大好きなソフトウェアエンジニア。最近はSF小説とミステリーを多く読んでいます。', 128, 94, 42)
ON CONFLICT (id) DO NOTHING;

-- Seed user posts (book_id now holds an external identifier e.g., ISBN)
INSERT INTO public.posts (id, profile_id, book_id, rating, comment, created_at)
VALUES
    ('e1111111-1111-1111-1111-111111111111', 'd3b07384-d113-4ec5-a587-f3e098a58f4a', '9780307465351', 5.0, 'SF小説の最高傑作！最初から最後まで興奮が収まらなかった。キャラクターの掛け合いも最高。', now() - INTERVAL '2 days'),
    ('e2222222-2222-2222-2222-222222222222', 'd3b07384-d113-4ec5-a587-f3e098a58f4a', '9784087250000', 4.5, '読むたびに新しい発見がある素晴らしい本。言葉の響きが美しく、切ないストーリーに胸が締め付けられます。', now() - INTERVAL '5 days'),
    ('e3333333-3333-3333-3333-333333333333', 'd3b07384-d113-4ec5-a587-f3e098a48f4a', '9784101029000', 4.0, '孤独と葛藤がストレートに伝わってくる。時代を超えて愛される理由がわかります。', now() - INTERVAL '10 days')
ON CONFLICT (id) DO NOTHING;

-- Seed collections and favorites (using external IDs)
INSERT INTO public.collections (profile_id, book_id, status)
VALUES
    ('d3b07384-d113-4ec5-a587-f3e098a58f4a', '9780307465351', 'read'),
    ('d3b07384-d113-4ec5-a587-f3e098a58f4a', '9784087250000', 'read'),
    ('d3b07384-d113-4ec5-a587-f3e098a58f4a', '9784101029000', 'read')
ON CONFLICT (profile_id, book_id) DO NOTHING;

INSERT INTO public.favorites (profile_id, book_id)
VALUES
    ('d3b07384-d113-4ec5-a587-f3e098a58f4a', '9780307465351'),
    ('d3b07384-d113-4ec5-a587-f3e098a58f4a', '9784087250000'),
    ('d3b07384-d113-4ec5-a587-f3e098a58f4a', '9784101029000')
ON CONFLICT (profile_id, book_id) DO NOTHING;

-- Helper function to increment read count (RPC callable)
CREATE OR REPLACE FUNCTION public.increment_read_count(user_id UUID)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    UPDATE public.profiles
    SET read_count = read_count + 1
    WHERE id = user_id;
END;
$$;

-- Trigger function to automatically update book rating_avg when reviews change (now calculates on external IDs)
CREATE OR REPLACE FUNCTION public.update_book_rating_avg()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    -- No books table; rating aggregation can be done in app layer if needed.
    RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER on_post_modified
    AFTER INSERT OR UPDATE OR DELETE ON public.posts
    FOR EACH ROW EXECUTE FUNCTION public.update_book_rating_avg();


-- Social graph, notifications, reactions and blocks.
-- Keep this snapshot aligned with the production migrations.
-- Social graph, reactions, notifications and blocking.
-- Public profiles are followed immediately. Private profiles require approval.

CREATE TABLE IF NOT EXISTS public.follows (
    follower_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    following_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('pending', 'accepted')),
    requested_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    responded_at TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (follower_id, following_id),
    CHECK (follower_id <> following_id)
);

CREATE TABLE IF NOT EXISTS public.blocks (
    blocker_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    blocked_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (blocker_id, blocked_id),
    CHECK (blocker_id <> blocked_id)
);

CREATE TABLE IF NOT EXISTS public.post_reactions (
    post_id UUID REFERENCES public.posts(id) ON DELETE CASCADE NOT NULL,
    profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (post_id, profile_id)
);

CREATE TABLE IF NOT EXISTS public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    actor_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('reaction', 'follow', 'follow_request')),
    post_id UUID REFERENCES public.posts(id) ON DELETE CASCADE,
    read_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CHECK (recipient_id <> actor_id),
    CHECK (
        (type = 'reaction' AND post_id IS NOT NULL)
        OR (type IN ('follow', 'follow_request') AND post_id IS NULL)
    )
);

CREATE INDEX IF NOT EXISTS follows_following_status_idx
    ON public.follows (following_id, status);
CREATE INDEX IF NOT EXISTS follows_follower_status_idx
    ON public.follows (follower_id, status);
CREATE INDEX IF NOT EXISTS blocks_blocked_idx
    ON public.blocks (blocked_id);
CREATE INDEX IF NOT EXISTS post_reactions_post_idx
    ON public.post_reactions (post_id);
CREATE INDEX IF NOT EXISTS notifications_recipient_created_idx
    ON public.notifications (recipient_id, created_at DESC);
CREATE INDEX IF NOT EXISTS notifications_recipient_unread_idx
    ON public.notifications (recipient_id, created_at DESC)
    WHERE read_at IS NULL;

ALTER TABLE public.follows ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_reactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.is_blocked_between(first_profile UUID, second_profile UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT CASE
        WHEN first_profile IS NULL OR second_profile IS NULL THEN false
        ELSE EXISTS (
            SELECT 1
            FROM public.blocks
            WHERE (blocker_id = first_profile AND blocked_id = second_profile)
               OR (blocker_id = second_profile AND blocked_id = first_profile)
        )
    END;
$$;

CREATE OR REPLACE FUNCTION public.can_view_profile_content(owner_profile UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.profiles AS owner
        WHERE owner.id = owner_profile
          AND (
              auth.uid() = owner.id
              OR (
                  NOT public.is_blocked_between(auth.uid(), owner.id)
                  AND (
                      owner.is_private = false
                      OR EXISTS (
                          SELECT 1
                          FROM public.follows
                          WHERE follower_id = auth.uid()
                            AND following_id = owner.id
                            AND status = 'accepted'
                      )
                  )
              )
          )
    );
$$;

DROP POLICY IF EXISTS "Allow public read access for posts" ON public.posts;
DROP POLICY IF EXISTS "Allow visible profile posts to be read" ON public.posts;
CREATE POLICY "Allow visible profile posts to be read"
    ON public.posts FOR SELECT
    USING (public.can_view_profile_content(profile_id));

DROP POLICY IF EXISTS "Allow public read access for favorites" ON public.favorites;
DROP POLICY IF EXISTS "Allow visible profile favorites to be read" ON public.favorites;
CREATE POLICY "Allow visible profile favorites to be read"
    ON public.favorites FOR SELECT
    USING (public.can_view_profile_content(profile_id));

DROP POLICY IF EXISTS "Allow public read access for collections" ON public.collections;
DROP POLICY IF EXISTS "Allow visible profile collections to be read" ON public.collections;
CREATE POLICY "Allow visible profile collections to be read"
    ON public.collections FOR SELECT
    USING (public.can_view_profile_content(profile_id));

DROP POLICY IF EXISTS "Users can view their follow relationships" ON public.follows;
CREATE POLICY "Users can view their follow relationships"
    ON public.follows FOR SELECT TO authenticated
    USING (auth.uid() = follower_id OR auth.uid() = following_id);

DROP POLICY IF EXISTS "Users can view blocks they created" ON public.blocks;
CREATE POLICY "Users can view blocks they created"
    ON public.blocks FOR SELECT TO authenticated
    USING (auth.uid() = blocker_id);

DROP POLICY IF EXISTS "Visible reactions can be read" ON public.post_reactions;
CREATE POLICY "Visible reactions can be read"
    ON public.post_reactions FOR SELECT
    USING (
        EXISTS (
            SELECT 1
            FROM public.posts
            WHERE posts.id = post_reactions.post_id
              AND public.can_view_profile_content(posts.profile_id)
        )
    );

DROP POLICY IF EXISTS "Users can add their own reactions" ON public.post_reactions;
CREATE POLICY "Users can add their own reactions"
    ON public.post_reactions FOR INSERT TO authenticated
    WITH CHECK (
        auth.uid() = profile_id
        AND EXISTS (
            SELECT 1
            FROM public.posts
            WHERE posts.id = post_reactions.post_id
              AND posts.profile_id <> auth.uid()
              AND public.can_view_profile_content(posts.profile_id)
        )
    );

DROP POLICY IF EXISTS "Users can remove their own reactions" ON public.post_reactions;
CREATE POLICY "Users can remove their own reactions"
    ON public.post_reactions FOR DELETE TO authenticated
    USING (auth.uid() = profile_id);

DROP POLICY IF EXISTS "Users can read their notifications" ON public.notifications;
CREATE POLICY "Users can read their notifications"
    ON public.notifications FOR SELECT TO authenticated
    USING (auth.uid() = recipient_id);

DROP POLICY IF EXISTS "Users can mark their notifications read" ON public.notifications;
CREATE POLICY "Users can mark their notifications read"
    ON public.notifications FOR UPDATE TO authenticated
    USING (auth.uid() = recipient_id)
    WITH CHECK (auth.uid() = recipient_id);

CREATE OR REPLACE FUNCTION public.update_follow_counts()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF TG_OP = 'INSERT' AND NEW.status = 'accepted' THEN
        UPDATE public.profiles
        SET following_count = COALESCE(following_count, 0) + 1
        WHERE id = NEW.follower_id;
        UPDATE public.profiles
        SET followers_count = COALESCE(followers_count, 0) + 1
        WHERE id = NEW.following_id;
    ELSIF TG_OP = 'UPDATE' AND OLD.status <> 'accepted' AND NEW.status = 'accepted' THEN
        UPDATE public.profiles
        SET following_count = COALESCE(following_count, 0) + 1
        WHERE id = NEW.follower_id;
        UPDATE public.profiles
        SET followers_count = COALESCE(followers_count, 0) + 1
        WHERE id = NEW.following_id;
    ELSIF TG_OP = 'UPDATE' AND OLD.status = 'accepted' AND NEW.status <> 'accepted' THEN
        UPDATE public.profiles
        SET following_count = GREATEST(COALESCE(following_count, 0) - 1, 0)
        WHERE id = OLD.follower_id;
        UPDATE public.profiles
        SET followers_count = GREATEST(COALESCE(followers_count, 0) - 1, 0)
        WHERE id = OLD.following_id;
    ELSIF TG_OP = 'DELETE' AND OLD.status = 'accepted' THEN
        UPDATE public.profiles
        SET following_count = GREATEST(COALESCE(following_count, 0) - 1, 0)
        WHERE id = OLD.follower_id;
        UPDATE public.profiles
        SET followers_count = GREATEST(COALESCE(followers_count, 0) - 1, 0)
        WHERE id = OLD.following_id;
    END IF;
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS follows_update_counts ON public.follows;
CREATE TRIGGER follows_update_counts
AFTER INSERT OR UPDATE OR DELETE ON public.follows
FOR EACH ROW EXECUTE FUNCTION public.update_follow_counts();

CREATE OR REPLACE FUNCTION public.create_follow_notification()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    INSERT INTO public.notifications (recipient_id, actor_id, type)
    VALUES (
        NEW.following_id,
        NEW.follower_id,
        CASE WHEN NEW.status = 'pending' THEN 'follow_request' ELSE 'follow' END
    );
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS follows_create_notification ON public.follows;
CREATE TRIGGER follows_create_notification
AFTER INSERT ON public.follows
FOR EACH ROW EXECUTE FUNCTION public.create_follow_notification();

CREATE OR REPLACE FUNCTION public.create_reaction_notification()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    post_owner UUID;
BEGIN
    SELECT profile_id INTO post_owner
    FROM public.posts
    WHERE id = NEW.post_id;

    IF post_owner IS NOT NULL AND post_owner <> NEW.profile_id THEN
        INSERT INTO public.notifications (recipient_id, actor_id, type, post_id)
        VALUES (post_owner, NEW.profile_id, 'reaction', NEW.post_id);
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS reactions_create_notification ON public.post_reactions;
CREATE TRIGGER reactions_create_notification
AFTER INSERT ON public.post_reactions
FOR EACH ROW EXECUTE FUNCTION public.create_reaction_notification();

CREATE OR REPLACE FUNCTION public.request_follow(target_profile UUID)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    requester UUID := auth.uid();
    target_is_private BOOLEAN;
    existing_status TEXT;
    next_status TEXT;
BEGIN
    IF requester IS NULL THEN
        RAISE EXCEPTION 'Authentication required';
    END IF;
    IF requester = target_profile THEN
        RAISE EXCEPTION 'Cannot follow yourself';
    END IF;
    IF public.is_blocked_between(requester, target_profile) THEN
        RAISE EXCEPTION 'Follow is not available';
    END IF;

    SELECT is_private INTO target_is_private
    FROM public.profiles
    WHERE id = target_profile;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Profile not found';
    END IF;

    SELECT status INTO existing_status
    FROM public.follows
    WHERE follower_id = requester AND following_id = target_profile;
    IF existing_status IS NOT NULL THEN
        RETURN existing_status;
    END IF;

    next_status := CASE WHEN target_is_private THEN 'pending' ELSE 'accepted' END;
    INSERT INTO public.follows (follower_id, following_id, status, responded_at)
    VALUES (
        requester,
        target_profile,
        next_status,
        CASE WHEN next_status = 'accepted' THEN timezone('utc'::text, now()) ELSE NULL END
    );
    RETURN next_status;
END;
$$;

CREATE OR REPLACE FUNCTION public.unfollow_profile(target_profile UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    DELETE FROM public.follows
    WHERE follower_id = auth.uid() AND following_id = target_profile;

    DELETE FROM public.notifications
    WHERE recipient_id = target_profile
      AND actor_id = auth.uid()
      AND type = 'follow_request'
      AND read_at IS NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.respond_follow_request(requester_profile UUID, approve BOOLEAN)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF approve THEN
        UPDATE public.follows
        SET status = 'accepted', responded_at = timezone('utc'::text, now())
        WHERE follower_id = requester_profile
          AND following_id = auth.uid()
          AND status = 'pending';
    ELSE
        DELETE FROM public.follows
        WHERE follower_id = requester_profile
          AND following_id = auth.uid()
          AND status = 'pending';
    END IF;

    UPDATE public.notifications
    SET read_at = COALESCE(read_at, timezone('utc'::text, now()))
    WHERE recipient_id = auth.uid()
      AND actor_id = requester_profile
      AND type = 'follow_request';
END;
$$;

CREATE OR REPLACE FUNCTION public.block_profile(target_profile UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    blocker UUID := auth.uid();
BEGIN
    IF blocker IS NULL OR blocker = target_profile THEN
        RAISE EXCEPTION 'Invalid block target';
    END IF;

    INSERT INTO public.blocks (blocker_id, blocked_id)
    VALUES (blocker, target_profile)
    ON CONFLICT DO NOTHING;

    DELETE FROM public.follows
    WHERE (follower_id = blocker AND following_id = target_profile)
       OR (follower_id = target_profile AND following_id = blocker);

    DELETE FROM public.notifications
    WHERE (recipient_id = blocker AND actor_id = target_profile)
       OR (recipient_id = target_profile AND actor_id = blocker);
END;
$$;

CREATE OR REPLACE FUNCTION public.unblock_profile(target_profile UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    DELETE FROM public.blocks
    WHERE blocker_id = auth.uid() AND blocked_id = target_profile;
END;
$$;

REVOKE ALL ON FUNCTION public.is_blocked_between(UUID, UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.can_view_profile_content(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.update_follow_counts() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.create_follow_notification() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.create_reaction_notification() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.request_follow(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.unfollow_profile(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.respond_follow_request(UUID, BOOLEAN) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.block_profile(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.unblock_profile(UUID) FROM PUBLIC;

GRANT SELECT ON public.follows TO authenticated;
GRANT SELECT ON public.blocks TO authenticated;
GRANT SELECT, INSERT, DELETE ON public.post_reactions TO authenticated;
GRANT SELECT, UPDATE ON public.notifications TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.notifications_id_seq TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_blocked_between(UUID, UUID) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.can_view_profile_content(UUID) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.request_follow(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.unfollow_profile(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.respond_follow_request(UUID, BOOLEAN) TO authenticated;
GRANT EXECUTE ON FUNCTION public.block_profile(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.unblock_profile(UUID) TO authenticated;

-- Typed reactions, post reporting and administrator moderation.

ALTER TABLE public.post_reactions
    ADD COLUMN IF NOT EXISTS reaction_type TEXT NOT NULL DEFAULT 'like';

ALTER TABLE public.post_reactions
    DROP CONSTRAINT IF EXISTS post_reactions_reaction_type_check;
ALTER TABLE public.post_reactions
    ADD CONSTRAINT post_reactions_reaction_type_check
    CHECK (reaction_type IN ('like', 'love', 'sad'));

ALTER TABLE public.profiles
    ADD COLUMN IF NOT EXISTS is_suspended BOOLEAN NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS public.app_admins (
    profile_id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.account_suspensions (
    profile_id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
    reason TEXT,
    suspended_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    suspended_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.moderation_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    reported_profile_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    post_id UUID REFERENCES public.posts(id) ON DELETE SET NULL,
    category TEXT NOT NULL CHECK (
        category IN ('spam', 'harassment', 'bullying', 'offensive', 'other')
    ),
    details TEXT CHECK (details IS NULL OR char_length(details) <= 1000),
    post_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'resolved')),
    resolution TEXT,
    resolved_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    resolved_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS moderation_reports_open_unique
    ON public.moderation_reports (reporter_id, post_id)
    WHERE status = 'open' AND post_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS moderation_reports_status_created_idx
    ON public.moderation_reports (status, created_at DESC);
CREATE INDEX IF NOT EXISTS moderation_reports_profile_idx
    ON public.moderation_reports (reported_profile_id, created_at DESC);

ALTER TABLE public.app_admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.account_suspensions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.moderation_reports ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.is_current_user_admin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1 FROM public.app_admins WHERE profile_id = auth.uid()
    );
$$;

CREATE OR REPLACE FUNCTION public.is_profile_active(profile UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT CASE
        WHEN profile IS NULL THEN true
        ELSE COALESCE((
            SELECT NOT is_suspended FROM public.profiles WHERE id = profile
        ), false)
    END;
$$;

CREATE OR REPLACE FUNCTION public.can_view_profile_content(owner_profile UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.profiles AS owner
        WHERE owner.id = owner_profile
          AND owner.is_suspended = false
          AND public.is_profile_active(auth.uid())
          AND (
              auth.uid() = owner.id
              OR (
                  NOT public.is_blocked_between(auth.uid(), owner.id)
                  AND (
                      owner.is_private = false
                      OR EXISTS (
                          SELECT 1
                          FROM public.follows
                          WHERE follower_id = auth.uid()
                            AND following_id = owner.id
                            AND status = 'accepted'
                      )
                  )
              )
          )
    );
$$;

DROP POLICY IF EXISTS "Users can add their own reactions" ON public.post_reactions;
CREATE POLICY "Users can add their own reactions"
    ON public.post_reactions FOR INSERT TO authenticated
    WITH CHECK (
        auth.uid() = profile_id
        AND public.is_profile_active(auth.uid())
        AND EXISTS (
            SELECT 1
            FROM public.posts
            WHERE posts.id = post_reactions.post_id
              AND posts.profile_id <> auth.uid()
              AND public.can_view_profile_content(posts.profile_id)
        )
    );

DROP POLICY IF EXISTS "Users can update their own reactions" ON public.post_reactions;
CREATE POLICY "Users can update their own reactions"
    ON public.post_reactions FOR UPDATE TO authenticated
    USING (auth.uid() = profile_id AND public.is_profile_active(auth.uid()))
    WITH CHECK (
        auth.uid() = profile_id
        AND public.is_profile_active(auth.uid())
        AND EXISTS (
            SELECT 1
            FROM public.posts
            WHERE posts.id = post_reactions.post_id
              AND posts.profile_id <> auth.uid()
              AND public.can_view_profile_content(posts.profile_id)
        )
    );

DROP POLICY IF EXISTS "Users can remove their own reactions" ON public.post_reactions;
CREATE POLICY "Users can remove their own reactions"
    ON public.post_reactions FOR DELETE TO authenticated
    USING (auth.uid() = profile_id AND public.is_profile_active(auth.uid()));

DROP POLICY IF EXISTS "Allow authenticated users to insert posts" ON public.posts;
CREATE POLICY "Allow authenticated users to insert posts"
    ON public.posts FOR INSERT TO authenticated
    WITH CHECK (auth.uid() = profile_id AND public.is_profile_active(auth.uid()));

DROP POLICY IF EXISTS "Allow users to update their own profile" ON public.profiles;
CREATE POLICY "Allow users to update their own profile"
    ON public.profiles FOR UPDATE TO authenticated
    USING (auth.uid() = id AND public.is_profile_active(auth.uid()))
    WITH CHECK (auth.uid() = id AND public.is_profile_active(auth.uid()));

DROP POLICY IF EXISTS "Allow authenticated users to insert/delete favorites" ON public.favorites;
CREATE POLICY "Allow authenticated users to insert/delete favorites"
    ON public.favorites FOR ALL TO authenticated
    USING (auth.uid() = profile_id AND public.is_profile_active(auth.uid()))
    WITH CHECK (auth.uid() = profile_id AND public.is_profile_active(auth.uid()));

DROP POLICY IF EXISTS "Allow authenticated users to insert/delete collections" ON public.collections;
CREATE POLICY "Allow authenticated users to insert/delete collections"
    ON public.collections FOR ALL TO authenticated
    USING (auth.uid() = profile_id AND public.is_profile_active(auth.uid()))
    WITH CHECK (auth.uid() = profile_id AND public.is_profile_active(auth.uid()));

DROP POLICY IF EXISTS "Administrators can read reports" ON public.moderation_reports;
CREATE POLICY "Administrators can read reports"
    ON public.moderation_reports FOR SELECT TO authenticated
    USING (public.is_current_user_admin());

DROP POLICY IF EXISTS "Users and administrators can read suspensions" ON public.account_suspensions;
CREATE POLICY "Users and administrators can read suspensions"
    ON public.account_suspensions FOR SELECT TO authenticated
    USING (auth.uid() = profile_id OR public.is_current_user_admin());

CREATE OR REPLACE FUNCTION public.request_follow(target_profile UUID)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    requester UUID := auth.uid();
    target_is_private BOOLEAN;
    existing_status TEXT;
    next_status TEXT;
BEGIN
    IF requester IS NULL OR NOT public.is_profile_active(requester) THEN
        RAISE EXCEPTION 'Account is not active';
    END IF;
    IF requester = target_profile THEN
        RAISE EXCEPTION 'Cannot follow yourself';
    END IF;
    IF NOT public.is_profile_active(target_profile) THEN
        RAISE EXCEPTION 'Profile is not available';
    END IF;
    IF public.is_blocked_between(requester, target_profile) THEN
        RAISE EXCEPTION 'Follow is not available';
    END IF;

    SELECT is_private INTO target_is_private
    FROM public.profiles
    WHERE id = target_profile;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Profile not found';
    END IF;

    SELECT status INTO existing_status
    FROM public.follows
    WHERE follower_id = requester AND following_id = target_profile;
    IF existing_status IS NOT NULL THEN
        RETURN existing_status;
    END IF;

    next_status := CASE WHEN target_is_private THEN 'pending' ELSE 'accepted' END;
    INSERT INTO public.follows (follower_id, following_id, status, responded_at)
    VALUES (
        requester,
        target_profile,
        next_status,
        CASE WHEN next_status = 'accepted' THEN timezone('utc'::text, now()) ELSE NULL END
    );
    RETURN next_status;
END;
$$;

CREATE OR REPLACE FUNCTION public.submit_post_report(
    target_post UUID,
    report_category TEXT,
    report_details TEXT DEFAULT NULL
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    reporter UUID := auth.uid();
    target_row public.posts%ROWTYPE;
    existing_id BIGINT;
    created_id BIGINT;
BEGIN
    IF reporter IS NULL OR NOT public.is_profile_active(reporter) THEN
        RAISE EXCEPTION 'Account is not active';
    END IF;
    IF report_category NOT IN ('spam', 'harassment', 'bullying', 'offensive', 'other') THEN
        RAISE EXCEPTION 'Invalid report category';
    END IF;
    IF report_details IS NOT NULL AND char_length(report_details) > 1000 THEN
        RAISE EXCEPTION 'Report details are too long';
    END IF;

    SELECT * INTO target_row FROM public.posts WHERE id = target_post;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Post not found';
    END IF;
    IF target_row.profile_id = reporter THEN
        RAISE EXCEPTION 'Cannot report your own post';
    END IF;

    SELECT id INTO existing_id
    FROM public.moderation_reports
    WHERE reporter_id = reporter AND post_id = target_post AND status = 'open';
    IF existing_id IS NOT NULL THEN
        RETURN existing_id;
    END IF;

    INSERT INTO public.moderation_reports (
        reporter_id,
        reported_profile_id,
        post_id,
        category,
        details,
        post_snapshot
    ) VALUES (
        reporter,
        target_row.profile_id,
        target_row.id,
        report_category,
        NULLIF(btrim(report_details), ''),
        jsonb_build_object(
            'post_id', target_row.id,
            'profile_id', target_row.profile_id,
            'book_id', target_row.book_id,
            'rating', target_row.rating,
            'review', target_row.comment,
            'created_at', target_row.created_at
        )
    ) RETURNING id INTO created_id;

    RETURN created_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.unfollow_profile(target_profile UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF NOT public.is_profile_active(auth.uid()) THEN
        RAISE EXCEPTION 'Account is not active';
    END IF;
    DELETE FROM public.follows
    WHERE follower_id = auth.uid() AND following_id = target_profile;
    DELETE FROM public.notifications
    WHERE recipient_id = target_profile
      AND actor_id = auth.uid()
      AND type = 'follow_request'
      AND read_at IS NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.respond_follow_request(requester_profile UUID, approve BOOLEAN)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF NOT public.is_profile_active(auth.uid()) THEN
        RAISE EXCEPTION 'Account is not active';
    END IF;
    IF approve AND NOT public.is_profile_active(requester_profile) THEN
        RAISE EXCEPTION 'Profile is not available';
    END IF;
    IF approve THEN
        UPDATE public.follows
        SET status = 'accepted', responded_at = timezone('utc'::text, now())
        WHERE follower_id = requester_profile
          AND following_id = auth.uid()
          AND status = 'pending';
    ELSE
        DELETE FROM public.follows
        WHERE follower_id = requester_profile
          AND following_id = auth.uid()
          AND status = 'pending';
    END IF;
    UPDATE public.notifications
    SET read_at = COALESCE(read_at, timezone('utc'::text, now()))
    WHERE recipient_id = auth.uid()
      AND actor_id = requester_profile
      AND type = 'follow_request';
END;
$$;

CREATE OR REPLACE FUNCTION public.block_profile(target_profile UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    blocker UUID := auth.uid();
BEGIN
    IF NOT public.is_profile_active(blocker) THEN
        RAISE EXCEPTION 'Account is not active';
    END IF;
    IF blocker = target_profile THEN
        RAISE EXCEPTION 'Invalid block target';
    END IF;
    INSERT INTO public.blocks (blocker_id, blocked_id)
    VALUES (blocker, target_profile)
    ON CONFLICT DO NOTHING;
    DELETE FROM public.follows
    WHERE (follower_id = blocker AND following_id = target_profile)
       OR (follower_id = target_profile AND following_id = blocker);
    DELETE FROM public.notifications
    WHERE (recipient_id = blocker AND actor_id = target_profile)
       OR (recipient_id = target_profile AND actor_id = blocker);
END;
$$;

CREATE OR REPLACE FUNCTION public.unblock_profile(target_profile UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF NOT public.is_profile_active(auth.uid()) THEN
        RAISE EXCEPTION 'Account is not active';
    END IF;
    DELETE FROM public.blocks
    WHERE blocker_id = auth.uid() AND blocked_id = target_profile;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_resolve_report(
    target_report BIGINT,
    resolution_note TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF NOT public.is_current_user_admin() THEN
        RAISE EXCEPTION 'Administrator access required';
    END IF;
    UPDATE public.moderation_reports
    SET status = 'resolved',
        resolution = NULLIF(btrim(resolution_note), ''),
        resolved_by = auth.uid(),
        resolved_at = timezone('utc'::text, now())
    WHERE id = target_report;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_delete_reported_post(target_report BIGINT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    target_post UUID;
BEGIN
    IF NOT public.is_current_user_admin() THEN
        RAISE EXCEPTION 'Administrator access required';
    END IF;

    SELECT post_id INTO target_post
    FROM public.moderation_reports
    WHERE id = target_report;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Report not found';
    END IF;

    UPDATE public.moderation_reports
    SET status = 'resolved',
        resolution = 'post_deleted',
        resolved_by = auth.uid(),
        resolved_at = timezone('utc'::text, now())
    WHERE status = 'open'
      AND (id = target_report OR post_id = target_post);

    IF target_post IS NOT NULL THEN
        DELETE FROM public.posts WHERE id = target_post;
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_set_account_suspension(
    target_profile UUID,
    suspend BOOLEAN,
    reason TEXT DEFAULT NULL
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF NOT public.is_current_user_admin() THEN
        RAISE EXCEPTION 'Administrator access required';
    END IF;
    IF target_profile = auth.uid() THEN
        RAISE EXCEPTION 'Cannot suspend your own administrator account';
    END IF;
    IF suspend AND EXISTS (
        SELECT 1 FROM public.app_admins WHERE profile_id = target_profile
    ) THEN
        RAISE EXCEPTION 'Cannot suspend an administrator account';
    END IF;

    UPDATE public.profiles
    SET is_suspended = suspend
    WHERE id = target_profile;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Profile not found';
    END IF;

    IF suspend THEN
        INSERT INTO public.account_suspensions (
            profile_id, reason, suspended_at, suspended_by
        ) VALUES (
            target_profile,
            NULLIF(btrim(reason), ''),
            timezone('utc'::text, now()),
            auth.uid()
        )
        ON CONFLICT (profile_id) DO UPDATE
        SET reason = EXCLUDED.reason,
            suspended_at = EXCLUDED.suspended_at,
            suspended_by = EXCLUDED.suspended_by;
        DELETE FROM public.follows
        WHERE follower_id = target_profile OR following_id = target_profile;
        DELETE FROM public.post_reactions WHERE profile_id = target_profile;
    ELSE
        DELETE FROM public.account_suspensions WHERE profile_id = target_profile;
    END IF;
END;
$$;

-- Users may edit public profile fields, but cannot clear their own suspension.
REVOKE UPDATE ON public.profiles FROM authenticated;
GRANT UPDATE (username, user_id, avatar_url, bio, is_private)
    ON public.profiles TO authenticated;

REVOKE ALL ON FUNCTION public.is_current_user_admin() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.is_profile_active(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.submit_post_report(UUID, TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_resolve_report(BIGINT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_delete_reported_post(BIGINT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_set_account_suspension(UUID, BOOLEAN, TEXT) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.is_current_user_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_profile_active(UUID) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.submit_post_report(UUID, TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_resolve_report(BIGINT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_delete_reported_post(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_account_suspension(UUID, BOOLEAN, TEXT) TO authenticated;
GRANT SELECT ON public.moderation_reports TO authenticated;
GRANT SELECT ON public.account_suspensions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.post_reactions TO authenticated;

COMMENT ON TABLE public.app_admins IS
    'Server-protected allowlist of profiles permitted to moderate Sharemarium.';
COMMENT ON TABLE public.moderation_reports IS
    'Post reports visible only to allowlisted administrators.';
COMMENT ON TABLE public.account_suspensions IS
    'Private suspension reasons visible only to the affected user and administrators.';

-- Privacy-settings password and settings-management functions.
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

ALTER TABLE public.profiles
    DROP CONSTRAINT IF EXISTS profiles_username_key;

CREATE TABLE IF NOT EXISTS public.privacy_password_credentials (
    profile_id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
    password_hash TEXT NOT NULL,
    failed_attempts SMALLINT NOT NULL DEFAULT 0 CHECK (failed_attempts BETWEEN 0 AND 20),
    locked_until TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.privacy_password_recovery_requests (
    profile_id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
    provider TEXT NOT NULL,
    requested_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.privacy_password_credentials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.privacy_password_recovery_requests ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.privacy_password_credentials FROM anon, authenticated;
REVOKE ALL ON public.privacy_password_recovery_requests FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.is_valid_privacy_password(candidate TEXT)
RETURNS BOOLEAN
LANGUAGE sql
IMMUTABLE
SET search_path = public
AS $$
    SELECT candidate IS NOT NULL
       AND char_length(candidate) BETWEEN 8 AND 20
       AND candidate ~ '[a-z]'
       AND candidate ~ '[A-Z]'
       AND candidate ~ '[0-9]';
$$;

CREATE OR REPLACE FUNCTION public.has_privacy_password()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, extensions
AS $$
    SELECT auth.uid() IS NOT NULL AND EXISTS (
        SELECT 1
        FROM public.privacy_password_credentials
        WHERE profile_id = auth.uid()
    );
$$;

CREATE OR REPLACE FUNCTION public.initialize_privacy_password(p_password TEXT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
BEGIN
    IF auth.uid() IS NULL THEN
        RAISE EXCEPTION 'Authentication required' USING ERRCODE = '42501';
    END IF;
    IF NOT public.is_valid_privacy_password(p_password) THEN
        RAISE EXCEPTION 'Invalid privacy password' USING ERRCODE = '23514';
    END IF;
    INSERT INTO public.privacy_password_credentials (profile_id, password_hash)
    VALUES (auth.uid(), extensions.crypt(p_password, extensions.gen_salt('bf', 12)));
END;
$$;

CREATE OR REPLACE FUNCTION public.verify_privacy_password(p_password TEXT)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    credential public.privacy_password_credentials%ROWTYPE;
    next_attempts SMALLINT;
BEGIN
    IF auth.uid() IS NULL THEN RETURN false; END IF;
    SELECT * INTO credential
    FROM public.privacy_password_credentials
    WHERE profile_id = auth.uid()
    FOR UPDATE;

    IF NOT FOUND OR credential.locked_until > timezone('utc'::text, now()) THEN
        RETURN false;
    END IF;

    IF credential.password_hash = extensions.crypt(p_password, credential.password_hash) THEN
        UPDATE public.privacy_password_credentials
        SET failed_attempts = 0, locked_until = NULL
        WHERE profile_id = auth.uid();
        RETURN true;
    END IF;

    next_attempts := credential.failed_attempts + 1;
    UPDATE public.privacy_password_credentials
    SET failed_attempts = CASE WHEN next_attempts >= 5 THEN 0 ELSE next_attempts END,
        locked_until = CASE
            WHEN next_attempts >= 5 THEN timezone('utc'::text, now()) + interval '15 minutes'
            ELSE NULL
        END
    WHERE profile_id = auth.uid();
    RETURN false;
END;
$$;

CREATE OR REPLACE FUNCTION public.update_public_profile(
    p_username TEXT,
    p_user_id TEXT,
    p_is_private BOOLEAN
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    normalized_user_id TEXT := lower(btrim(p_user_id));
BEGIN
    IF auth.uid() IS NULL THEN
        RAISE EXCEPTION 'Authentication required' USING ERRCODE = '42501';
    END IF;
    IF char_length(btrim(p_username)) NOT BETWEEN 1 AND 30
       OR normalized_user_id !~ '^[a-z0-9_]{3,20}$'
       OR normalized_user_id IN (
           'admin', 'administrator', 'support', 'sharemarium', 'system', 'official'
       ) THEN
        RAISE EXCEPTION 'Invalid profile data' USING ERRCODE = '23514';
    END IF;
    UPDATE public.profiles
    SET username = btrim(p_username),
        user_id = normalized_user_id,
        is_private = p_is_private
    WHERE id = auth.uid();
END;
$$;

CREATE OR REPLACE FUNCTION public.update_private_account_details(
    p_password TEXT,
    p_full_name TEXT,
    p_birth_date DATE,
    p_phone_number TEXT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    normalized_phone TEXT := regexp_replace(p_phone_number, '[^0-9+]', '', 'g');
BEGIN
    IF NOT public.verify_privacy_password(p_password) THEN
        RETURN false;
    END IF;
    IF char_length(btrim(p_full_name)) NOT BETWEEN 1 AND 100
       OR p_birth_date < DATE '1900-01-01'
       OR p_birth_date > CURRENT_DATE
       OR normalized_phone !~ '^\+?[0-9]{7,15}$' THEN
        RAISE EXCEPTION 'Invalid private account data' USING ERRCODE = '23514';
    END IF;
    UPDATE public.account_details
    SET full_name = btrim(p_full_name),
        birth_date = p_birth_date,
        phone_number = normalized_phone,
        phone_verified_at = CASE
            WHEN phone_number = normalized_phone THEN phone_verified_at
            ELSE NULL
        END,
        updated_at = timezone('utc'::text, now())
    WHERE profile_id = auth.uid();
    RETURN FOUND;
END;
$$;

CREATE OR REPLACE FUNCTION public.change_privacy_password(
    p_current_password TEXT,
    p_new_password TEXT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
BEGIN
    IF NOT public.is_valid_privacy_password(p_new_password) THEN
        RAISE EXCEPTION 'Invalid privacy password' USING ERRCODE = '23514';
    END IF;
    IF NOT public.verify_privacy_password(p_current_password) THEN
        RETURN false;
    END IF;
    UPDATE public.privacy_password_credentials
    SET password_hash = extensions.crypt(p_new_password, extensions.gen_salt('bf', 12)),
        failed_attempts = 0,
        locked_until = NULL,
        updated_at = timezone('utc'::text, now())
    WHERE profile_id = auth.uid();
    RETURN true;
END;
$$;

CREATE OR REPLACE FUNCTION public.begin_privacy_password_recovery()
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    current_provider TEXT := auth.jwt() -> 'app_metadata' ->> 'provider';
BEGIN
    IF auth.uid() IS NULL THEN
        RAISE EXCEPTION 'Authentication required' USING ERRCODE = '42501';
    END IF;
    IF current_provider NOT IN ('google', 'twitter', 'x', 'facebook', 'apple', 'discord') THEN
        RAISE EXCEPTION 'Unsupported recovery provider' USING ERRCODE = '22023';
    END IF;
    INSERT INTO public.privacy_password_recovery_requests (
        profile_id, provider, requested_at
    ) VALUES (
        auth.uid(), current_provider, timezone('utc'::text, now())
    )
    ON CONFLICT (profile_id) DO UPDATE
    SET provider = EXCLUDED.provider,
        requested_at = EXCLUDED.requested_at;
END;
$$;

CREATE OR REPLACE FUNCTION public.reset_privacy_password_after_reauthentication(
    p_new_password TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    recovery public.privacy_password_recovery_requests%ROWTYPE;
    has_recent_oauth BOOLEAN;
BEGIN
    IF NOT public.is_valid_privacy_password(p_new_password) THEN
        RAISE EXCEPTION 'Invalid privacy password' USING ERRCODE = '23514';
    END IF;
    SELECT * INTO recovery
    FROM public.privacy_password_recovery_requests
    WHERE profile_id = auth.uid()
      AND requested_at >= timezone('utc'::text, now()) - interval '15 minutes';
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Recovery request expired' USING ERRCODE = '42501';
    END IF;
    IF (auth.jwt() -> 'app_metadata' ->> 'provider') IS DISTINCT FROM recovery.provider THEN
        RAISE EXCEPTION 'Recovery provider mismatch' USING ERRCODE = '42501';
    END IF;

    SELECT EXISTS (
        SELECT 1
        FROM jsonb_array_elements(COALESCE(auth.jwt() -> 'amr', '[]'::jsonb)) AS entry
        WHERE entry ->> 'method' = 'oauth'
          AND to_timestamp((entry ->> 'timestamp')::double precision)
              >= recovery.requested_at - interval '5 seconds'
    ) INTO has_recent_oauth;
    IF NOT has_recent_oauth THEN
        RAISE EXCEPTION 'Fresh OAuth authentication required' USING ERRCODE = '42501';
    END IF;

    UPDATE public.privacy_password_credentials
    SET password_hash = extensions.crypt(p_new_password, extensions.gen_salt('bf', 12)),
        failed_attempts = 0,
        locked_until = NULL,
        updated_at = timezone('utc'::text, now())
    WHERE profile_id = auth.uid();
    DELETE FROM public.privacy_password_recovery_requests
    WHERE profile_id = auth.uid();
END;
$$;

DROP FUNCTION IF EXISTS public.complete_registration(TEXT, DATE, TEXT, TEXT, TEXT);
CREATE OR REPLACE FUNCTION public.complete_registration(
    p_full_name TEXT,
    p_birth_date DATE,
    p_phone_number TEXT,
    p_username TEXT,
    p_user_id TEXT,
    p_privacy_password TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    current_profile_id UUID := auth.uid();
    normalized_user_id TEXT := lower(btrim(p_user_id));
    normalized_phone TEXT := regexp_replace(p_phone_number, '[^0-9+]', '', 'g');
BEGIN
    IF current_profile_id IS NULL THEN
        RAISE EXCEPTION 'Authentication required' USING ERRCODE = '42501';
    END IF;
    IF char_length(btrim(p_full_name)) NOT BETWEEN 1 AND 100
       OR p_birth_date < DATE '1900-01-01'
       OR p_birth_date > CURRENT_DATE
       OR normalized_phone !~ '^\+?[0-9]{7,15}$'
       OR char_length(btrim(p_username)) NOT BETWEEN 1 AND 30
       OR normalized_user_id !~ '^[a-z0-9_]{3,20}$'
       OR NOT public.is_valid_privacy_password(p_privacy_password) THEN
        RAISE EXCEPTION 'Invalid registration data' USING ERRCODE = '23514';
    END IF;
    IF normalized_user_id IN (
        'admin', 'administrator', 'support', 'sharemarium', 'system', 'official'
    ) THEN
        RAISE EXCEPTION 'Reserved user ID' USING ERRCODE = '23514';
    END IF;

    UPDATE public.profiles
    SET username = btrim(p_username), user_id = normalized_user_id
    WHERE id = current_profile_id;

    INSERT INTO public.account_details (
        profile_id, full_name, birth_date, phone_number
    ) VALUES (
        current_profile_id, btrim(p_full_name), p_birth_date, normalized_phone
    )
    ON CONFLICT (profile_id) DO UPDATE
    SET full_name = EXCLUDED.full_name,
        birth_date = EXCLUDED.birth_date,
        phone_number = EXCLUDED.phone_number,
        phone_verified_at = CASE
            WHEN public.account_details.phone_number = EXCLUDED.phone_number
                THEN public.account_details.phone_verified_at
            ELSE NULL
        END,
        updated_at = timezone('utc'::text, now());

    INSERT INTO public.privacy_password_credentials (profile_id, password_hash)
    VALUES (
        current_profile_id,
        extensions.crypt(p_privacy_password, extensions.gen_salt('bf', 12))
    )
    ON CONFLICT (profile_id) DO NOTHING;
END;
$$;

REVOKE ALL ON FUNCTION public.is_valid_privacy_password(TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.has_privacy_password() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.initialize_privacy_password(TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.verify_privacy_password(TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.update_public_profile(TEXT, TEXT, BOOLEAN) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.update_private_account_details(TEXT, TEXT, DATE, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.change_privacy_password(TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.begin_privacy_password_recovery() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.reset_privacy_password_after_reauthentication(TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.complete_registration(TEXT, DATE, TEXT, TEXT, TEXT, TEXT) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.has_privacy_password() TO authenticated;
GRANT EXECUTE ON FUNCTION public.initialize_privacy_password(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.verify_privacy_password(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_public_profile(TEXT, TEXT, BOOLEAN) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_private_account_details(TEXT, TEXT, DATE, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.change_privacy_password(TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.begin_privacy_password_recovery() TO authenticated;
GRANT EXECUTE ON FUNCTION public.reset_privacy_password_after_reauthentication(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.complete_registration(TEXT, DATE, TEXT, TEXT, TEXT, TEXT) TO authenticated;

DROP POLICY IF EXISTS "Users can update their own account details" ON public.account_details;
