/* Updated schema for API‑only book data */
-- Create profiles table
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    user_id TEXT NOT NULL CHECK (
        user_id = lower(user_id)
        AND user_id ~ '^[a-z0-9_]{3,20}$'
    ),
    avatar_url TEXT,
    bio TEXT,
    followers_count INTEGER DEFAULT 0,
    following_count INTEGER DEFAULT 0,
    read_count INTEGER DEFAULT 0,
    is_private BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE UNIQUE INDEX IF NOT EXISTS profiles_user_id_lower_unique
    ON public.profiles (lower(user_id));

-- Legal name, date of birth and phone number must never be publicly readable.
CREATE TABLE IF NOT EXISTS public.account_details (
    profile_id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
    full_name TEXT NOT NULL CHECK (char_length(btrim(full_name)) BETWEEN 1 AND 100),
    birth_date DATE NOT NULL CHECK (
        birth_date >= DATE '1900-01-01'
        AND birth_date <= CURRENT_DATE
    ),
    phone_number TEXT NOT NULL CHECK (phone_number ~ '^\+?[0-9]{7,15}$'),
    phone_verified_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.account_details ENABLE ROW LEVEL SECURITY;

-- NOTE: books table removed; external API provides book data.

-- Posts now reference external book IDs (ISBN or other) as plain TEXT
CREATE TABLE IF NOT EXISTS public.posts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    book_id TEXT NOT NULL,
    rating DOUBLE PRECISION NOT NULL CHECK (rating >= 1.0 AND rating <= 5.0),
    comment TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;

-- Favorites reference external book IDs as TEXT
CREATE TABLE IF NOT EXISTS public.favorites (
    profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    book_id TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (profile_id, book_id)
);

ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;

-- Collections track reading status for external book IDs as TEXT
CREATE TABLE IF NOT EXISTS public.collections (
    profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    book_id TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('to_read', 'reading', 'read')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (profile_id, book_id)
);

ALTER TABLE public.collections ENABLE ROW LEVEL SECURITY;

-- Legal consent history for the exact document bundle accepted by a user.
CREATE TABLE IF NOT EXISTS public.legal_consents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    bundle_version TEXT NOT NULL,
    terms_version TEXT NOT NULL,
    privacy_version TEXT NOT NULL,
    community_guidelines_version TEXT NOT NULL,
    infringement_policy_version TEXT NOT NULL,
    external_transmission_version TEXT NOT NULL,
    auth_provider TEXT,
    accepted_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE (profile_id, bundle_version)
);

ALTER TABLE public.legal_consents ENABLE ROW LEVEL SECURITY;

-- Contact requests are write-only from the public app and readable in the
-- Supabase Dashboard by the operator.
CREATE TABLE IF NOT EXISTS public.contact_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    email TEXT NOT NULL CHECK (char_length(email) BETWEEN 3 AND 320),
    category TEXT NOT NULL CHECK (
        category IN ('general', 'privacy', 'infringement', 'report', 'account', 'other')
    ),
    subject TEXT NOT NULL CHECK (char_length(subject) BETWEEN 1 AND 120),
    message TEXT NOT NULL CHECK (char_length(message) BETWEEN 1 AND 4000),
    status TEXT NOT NULL DEFAULT 'received' CHECK (status IN ('received', 'in_progress', 'closed')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.contact_requests ENABLE ROW LEVEL SECURITY;

-- RLS Policies (same as before)
CREATE POLICY "Allow public read access for profiles" ON public.profiles
    FOR SELECT USING (true);

CREATE POLICY "Allow users to update their own profile" ON public.profiles
    FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Allow users to insert their own profile" ON public.profiles
    FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can read their own account details" ON public.account_details
    FOR SELECT TO authenticated USING (auth.uid() = profile_id);

CREATE POLICY "Users can insert their own account details" ON public.account_details
    FOR INSERT TO authenticated WITH CHECK (auth.uid() = profile_id);

CREATE POLICY "Users can update their own account details" ON public.account_details
    FOR UPDATE TO authenticated
    USING (auth.uid() = profile_id)
    WITH CHECK (auth.uid() = profile_id);

CREATE POLICY "Allow visible profile posts to be read" ON public.posts
    FOR SELECT USING (
        auth.uid() = profile_id
        OR EXISTS (
            SELECT 1
            FROM public.profiles AS profile
            WHERE profile.id = posts.profile_id
              AND profile.is_private = false
        )
    );

CREATE POLICY "Allow authenticated users to insert posts" ON public.posts
    FOR INSERT WITH CHECK (auth.uid() = profile_id);

CREATE POLICY "Allow visible profile favorites to be read" ON public.favorites
    FOR SELECT USING (
        auth.uid() = profile_id
        OR EXISTS (
            SELECT 1
            FROM public.profiles AS profile
            WHERE profile.id = favorites.profile_id
              AND profile.is_private = false
        )
    );

CREATE POLICY "Allow authenticated users to insert/delete favorites" ON public.favorites
    FOR ALL USING (auth.uid() = profile_id);

CREATE POLICY "Allow visible profile collections to be read" ON public.collections
    FOR SELECT USING (
        auth.uid() = profile_id
        OR EXISTS (
            SELECT 1
            FROM public.profiles AS profile
            WHERE profile.id = collections.profile_id
              AND profile.is_private = false
        )
    );

CREATE POLICY "Allow authenticated users to insert/delete collections" ON public.collections
    FOR ALL USING (auth.uid() = profile_id);

CREATE POLICY "Users can read their own legal consents" ON public.legal_consents
    FOR SELECT USING (auth.uid() = profile_id);

CREATE POLICY "Users can insert their own legal consents" ON public.legal_consents
    FOR INSERT WITH CHECK (auth.uid() = profile_id);

CREATE POLICY "Anyone can submit a contact request" ON public.contact_requests
    FOR INSERT TO anon, authenticated
    WITH CHECK (
        status = 'received'
        AND (profile_id IS NULL OR auth.uid() = profile_id)
    );

GRANT SELECT, INSERT ON public.legal_consents TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.legal_consents_id_seq TO authenticated;
GRANT INSERT ON public.contact_requests TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.contact_requests_id_seq TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.account_details TO authenticated;

CREATE OR REPLACE FUNCTION public.complete_registration(
    p_full_name TEXT,
    p_birth_date DATE,
    p_phone_number TEXT,
    p_username TEXT,
    p_user_id TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
    current_profile_id UUID := auth.uid();
    normalized_user_id TEXT := lower(btrim(p_user_id));
    normalized_phone TEXT := regexp_replace(p_phone_number, '[^0-9+]', '', 'g');
BEGIN
    IF current_profile_id IS NULL THEN
        RAISE EXCEPTION 'Authentication required' USING ERRCODE = '42501';
    END IF;

    IF char_length(btrim(p_full_name)) NOT BETWEEN 1 AND 100
        OR p_birth_date < DATE '1900-01-01'
        OR p_birth_date > CURRENT_DATE
        OR normalized_phone !~ '^\+?[0-9]{7,15}$'
        OR char_length(btrim(p_username)) NOT BETWEEN 1 AND 30
        OR normalized_user_id !~ '^[a-z0-9_]{3,20}$'
    THEN
        RAISE EXCEPTION 'Invalid registration data' USING ERRCODE = '23514';
    END IF;

    IF normalized_user_id IN (
        'admin', 'administrator', 'support', 'sharemarium', 'system', 'official'
    ) THEN
        RAISE EXCEPTION 'Reserved user ID' USING ERRCODE = '23514';
    END IF;

    UPDATE public.profiles
    SET username = btrim(p_username), user_id = normalized_user_id
    WHERE id = current_profile_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Profile not found' USING ERRCODE = 'P0002';
    END IF;

    INSERT INTO public.account_details (
        profile_id, full_name, birth_date, phone_number
    ) VALUES (
        current_profile_id, btrim(p_full_name), p_birth_date, normalized_phone
    )
    ON CONFLICT (profile_id) DO UPDATE
    SET full_name = EXCLUDED.full_name,
        birth_date = EXCLUDED.birth_date,
        phone_number = EXCLUDED.phone_number,
        phone_verified_at = CASE
            WHEN public.account_details.phone_number = EXCLUDED.phone_number
                THEN public.account_details.phone_verified_at
            ELSE NULL
        END,
        updated_at = timezone('utc'::text, now());
END;
$$;

REVOKE ALL ON FUNCTION public.complete_registration(TEXT, DATE, TEXT, TEXT, TEXT)
    FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.complete_registration(TEXT, DATE, TEXT, TEXT, TEXT)
    TO authenticated;

-- Seed data now only includes profiles (books are fetched from external APIs)
INSERT INTO public.profiles (id, username, user_id, avatar_url, bio, followers_count, following_count, read_count)
VALUES
    ('d3b07384-d113-4ec5-a587-f3e098a58f4a', 'ryu_booklover', 'ryu_booklover', 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80', '本を読むのが大好きなソフトウェアエンジニア。最近はSF小説とミステリーを多く読んでいます。', 128, 94, 42)
ON CONFLICT (id) DO NOTHING;

-- Seed user posts (book_id now holds an external identifier e.g., ISBN)
INSERT INTO public.posts (id, profile_id, book_id, rating, comment, created_at)
VALUES
    ('e1111111-1111-1111-1111-111111111111', 'd3b07384-d113-4ec5-a587-f3e098a58f4a', '9780307465351', 5.0, 'SF小説の最高傑作！最初から最後まで興奮が収まらなかった。キャラクターの掛け合いも最高。', now() - INTERVAL '2 days'),
    ('e2222222-2222-2222-2222-222222222222', 'd3b07384-d113-4ec5-a587-f3e098a58f4a', '9784087250000', 4.5, '読むたびに新しい発見がある素晴らしい本。言葉の響きが美しく、切ないストーリーに胸が締め付けられます。', now() - INTERVAL '5 days'),
    ('e3333333-3333-3333-3333-333333333333', 'd3b07384-d113-4ec5-a587-f3e098a48f4a', '9784101029000', 4.0, '孤独と葛藤がストレートに伝わってくる。時代を超えて愛される理由がわかります。', now() - INTERVAL '10 days')
ON CONFLICT (id) DO NOTHING;

-- Seed collections and favorites (using external IDs)
INSERT INTO public.collections (profile_id, book_id, status)
VALUES
    ('d3b07384-d113-4ec5-a587-f3e098a58f4a', '9780307465351', 'read'),
    ('d3b07384-d113-4ec5-a587-f3e098a58f4a', '9784087250000', 'read'),
    ('d3b07384-d113-4ec5-a587-f3e098a58f4a', '9784101029000', 'read')
ON CONFLICT (profile_id, book_id) DO NOTHING;

INSERT INTO public.favorites (profile_id, book_id)
VALUES
    ('d3b07384-d113-4ec5-a587-f3e098a58f4a', '9780307465351'),
    ('d3b07384-d113-4ec5-a587-f3e098a58f4a', '9784087250000'),
    ('d3b07384-d113-4ec5-a587-f3e098a58f4a', '9784101029000')
ON CONFLICT (profile_id, book_id) DO NOTHING;

-- Helper function to increment read count (RPC callable)
CREATE OR REPLACE FUNCTION public.increment_read_count(user_id UUID)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    UPDATE public.profiles
    SET read_count = read_count + 1
    WHERE id = user_id;
END;
$$;

-- Trigger function to automatically update book rating_avg when reviews change (now calculates on external IDs)
CREATE OR REPLACE FUNCTION public.update_book_rating_avg()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    -- No books table; rating aggregation can be done in app layer if needed.
    RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER on_post_modified
    AFTER INSERT OR UPDATE OR DELETE ON public.posts
    FOR EACH ROW EXECUTE FUNCTION public.update_book_rating_avg();
