-- Social graph, reactions, notifications and blocking.
-- Public profiles are followed immediately. Private profiles require approval.

CREATE TABLE IF NOT EXISTS public.follows (
    follower_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    following_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('pending', 'accepted')),
    requested_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    responded_at TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (follower_id, following_id),
    CHECK (follower_id <> following_id)
);

CREATE TABLE IF NOT EXISTS public.blocks (
    blocker_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    blocked_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (blocker_id, blocked_id),
    CHECK (blocker_id <> blocked_id)
);

CREATE TABLE IF NOT EXISTS public.post_reactions (
    post_id UUID REFERENCES public.posts(id) ON DELETE CASCADE NOT NULL,
    profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (post_id, profile_id)
);

CREATE TABLE IF NOT EXISTS public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    actor_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('reaction', 'follow', 'follow_request')),
    post_id UUID REFERENCES public.posts(id) ON DELETE CASCADE,
    read_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CHECK (recipient_id <> actor_id),
    CHECK (
        (type = 'reaction' AND post_id IS NOT NULL)
        OR (type IN ('follow', 'follow_request') AND post_id IS NULL)
    )
);

CREATE INDEX IF NOT EXISTS follows_following_status_idx
    ON public.follows (following_id, status);
CREATE INDEX IF NOT EXISTS follows_follower_status_idx
    ON public.follows (follower_id, status);
CREATE INDEX IF NOT EXISTS blocks_blocked_idx
    ON public.blocks (blocked_id);
CREATE INDEX IF NOT EXISTS post_reactions_post_idx
    ON public.post_reactions (post_id);
CREATE INDEX IF NOT EXISTS notifications_recipient_created_idx
    ON public.notifications (recipient_id, created_at DESC);
CREATE INDEX IF NOT EXISTS notifications_recipient_unread_idx
    ON public.notifications (recipient_id, created_at DESC)
    WHERE read_at IS NULL;

ALTER TABLE public.follows ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_reactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.is_blocked_between(first_profile UUID, second_profile UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT CASE
        WHEN first_profile IS NULL OR second_profile IS NULL THEN false
        ELSE EXISTS (
            SELECT 1
            FROM public.blocks
            WHERE (blocker_id = first_profile AND blocked_id = second_profile)
               OR (blocker_id = second_profile AND blocked_id = first_profile)
        )
    END;
$$;

CREATE OR REPLACE FUNCTION public.can_view_profile_content(owner_profile UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.profiles AS owner
        WHERE owner.id = owner_profile
          AND (
              auth.uid() = owner.id
              OR (
                  NOT public.is_blocked_between(auth.uid(), owner.id)
                  AND (
                      owner.is_private = false
                      OR EXISTS (
                          SELECT 1
                          FROM public.follows
                          WHERE follower_id = auth.uid()
                            AND following_id = owner.id
                            AND status = 'accepted'
                      )
                  )
              )
          )
    );
$$;

DROP POLICY IF EXISTS "Allow public read access for posts" ON public.posts;
DROP POLICY IF EXISTS "Allow visible profile posts to be read" ON public.posts;
CREATE POLICY "Allow visible profile posts to be read"
    ON public.posts FOR SELECT
    USING (public.can_view_profile_content(profile_id));

DROP POLICY IF EXISTS "Allow public read access for favorites" ON public.favorites;
DROP POLICY IF EXISTS "Allow visible profile favorites to be read" ON public.favorites;
CREATE POLICY "Allow visible profile favorites to be read"
    ON public.favorites FOR SELECT
    USING (public.can_view_profile_content(profile_id));

DROP POLICY IF EXISTS "Allow public read access for collections" ON public.collections;
DROP POLICY IF EXISTS "Allow visible profile collections to be read" ON public.collections;
CREATE POLICY "Allow visible profile collections to be read"
    ON public.collections FOR SELECT
    USING (public.can_view_profile_content(profile_id));

DROP POLICY IF EXISTS "Users can view their follow relationships" ON public.follows;
CREATE POLICY "Users can view their follow relationships"
    ON public.follows FOR SELECT TO authenticated
    USING (auth.uid() = follower_id OR auth.uid() = following_id);

DROP POLICY IF EXISTS "Users can view blocks they created" ON public.blocks;
CREATE POLICY "Users can view blocks they created"
    ON public.blocks FOR SELECT TO authenticated
    USING (auth.uid() = blocker_id);

DROP POLICY IF EXISTS "Visible reactions can be read" ON public.post_reactions;
CREATE POLICY "Visible reactions can be read"
    ON public.post_reactions FOR SELECT
    USING (
        EXISTS (
            SELECT 1
            FROM public.posts
            WHERE posts.id = post_reactions.post_id
              AND public.can_view_profile_content(posts.profile_id)
        )
    );

DROP POLICY IF EXISTS "Users can add their own reactions" ON public.post_reactions;
CREATE POLICY "Users can add their own reactions"
    ON public.post_reactions FOR INSERT TO authenticated
    WITH CHECK (
        auth.uid() = profile_id
        AND EXISTS (
            SELECT 1
            FROM public.posts
            WHERE posts.id = post_reactions.post_id
              AND posts.profile_id <> auth.uid()
              AND public.can_view_profile_content(posts.profile_id)
        )
    );

DROP POLICY IF EXISTS "Users can remove their own reactions" ON public.post_reactions;
CREATE POLICY "Users can remove their own reactions"
    ON public.post_reactions FOR DELETE TO authenticated
    USING (auth.uid() = profile_id);

DROP POLICY IF EXISTS "Users can read their notifications" ON public.notifications;
CREATE POLICY "Users can read their notifications"
    ON public.notifications FOR SELECT TO authenticated
    USING (auth.uid() = recipient_id);

DROP POLICY IF EXISTS "Users can mark their notifications read" ON public.notifications;
CREATE POLICY "Users can mark their notifications read"
    ON public.notifications FOR UPDATE TO authenticated
    USING (auth.uid() = recipient_id)
    WITH CHECK (auth.uid() = recipient_id);

CREATE OR REPLACE FUNCTION public.update_follow_counts()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF TG_OP = 'INSERT' AND NEW.status = 'accepted' THEN
        UPDATE public.profiles
        SET following_count = COALESCE(following_count, 0) + 1
        WHERE id = NEW.follower_id;
        UPDATE public.profiles
        SET followers_count = COALESCE(followers_count, 0) + 1
        WHERE id = NEW.following_id;
    ELSIF TG_OP = 'UPDATE' AND OLD.status <> 'accepted' AND NEW.status = 'accepted' THEN
        UPDATE public.profiles
        SET following_count = COALESCE(following_count, 0) + 1
        WHERE id = NEW.follower_id;
        UPDATE public.profiles
        SET followers_count = COALESCE(followers_count, 0) + 1
        WHERE id = NEW.following_id;
    ELSIF TG_OP = 'UPDATE' AND OLD.status = 'accepted' AND NEW.status <> 'accepted' THEN
        UPDATE public.profiles
        SET following_count = GREATEST(COALESCE(following_count, 0) - 1, 0)
        WHERE id = OLD.follower_id;
        UPDATE public.profiles
        SET followers_count = GREATEST(COALESCE(followers_count, 0) - 1, 0)
        WHERE id = OLD.following_id;
    ELSIF TG_OP = 'DELETE' AND OLD.status = 'accepted' THEN
        UPDATE public.profiles
        SET following_count = GREATEST(COALESCE(following_count, 0) - 1, 0)
        WHERE id = OLD.follower_id;
        UPDATE public.profiles
        SET followers_count = GREATEST(COALESCE(followers_count, 0) - 1, 0)
        WHERE id = OLD.following_id;
    END IF;
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS follows_update_counts ON public.follows;
CREATE TRIGGER follows_update_counts
AFTER INSERT OR UPDATE OR DELETE ON public.follows
FOR EACH ROW EXECUTE FUNCTION public.update_follow_counts();

CREATE OR REPLACE FUNCTION public.create_follow_notification()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    INSERT INTO public.notifications (recipient_id, actor_id, type)
    VALUES (
        NEW.following_id,
        NEW.follower_id,
        CASE WHEN NEW.status = 'pending' THEN 'follow_request' ELSE 'follow' END
    );
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS follows_create_notification ON public.follows;
CREATE TRIGGER follows_create_notification
AFTER INSERT ON public.follows
FOR EACH ROW EXECUTE FUNCTION public.create_follow_notification();

CREATE OR REPLACE FUNCTION public.create_reaction_notification()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    post_owner UUID;
BEGIN
    SELECT profile_id INTO post_owner
    FROM public.posts
    WHERE id = NEW.post_id;

    IF post_owner IS NOT NULL AND post_owner <> NEW.profile_id THEN
        INSERT INTO public.notifications (recipient_id, actor_id, type, post_id)
        VALUES (post_owner, NEW.profile_id, 'reaction', NEW.post_id);
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS reactions_create_notification ON public.post_reactions;
CREATE TRIGGER reactions_create_notification
AFTER INSERT ON public.post_reactions
FOR EACH ROW EXECUTE FUNCTION public.create_reaction_notification();

CREATE OR REPLACE FUNCTION public.request_follow(target_profile UUID)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    requester UUID := auth.uid();
    target_is_private BOOLEAN;
    existing_status TEXT;
    next_status TEXT;
BEGIN
    IF requester IS NULL THEN
        RAISE EXCEPTION 'Authentication required';
    END IF;
    IF requester = target_profile THEN
        RAISE EXCEPTION 'Cannot follow yourself';
    END IF;
    IF public.is_blocked_between(requester, target_profile) THEN
        RAISE EXCEPTION 'Follow is not available';
    END IF;

    SELECT is_private INTO target_is_private
    FROM public.profiles
    WHERE id = target_profile;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Profile not found';
    END IF;

    SELECT status INTO existing_status
    FROM public.follows
    WHERE follower_id = requester AND following_id = target_profile;
    IF existing_status IS NOT NULL THEN
        RETURN existing_status;
    END IF;

    next_status := CASE WHEN target_is_private THEN 'pending' ELSE 'accepted' END;
    INSERT INTO public.follows (follower_id, following_id, status, responded_at)
    VALUES (
        requester,
        target_profile,
        next_status,
        CASE WHEN next_status = 'accepted' THEN timezone('utc'::text, now()) ELSE NULL END
    );
    RETURN next_status;
END;
$$;

CREATE OR REPLACE FUNCTION public.unfollow_profile(target_profile UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    DELETE FROM public.follows
    WHERE follower_id = auth.uid() AND following_id = target_profile;

    DELETE FROM public.notifications
    WHERE recipient_id = target_profile
      AND actor_id = auth.uid()
      AND type = 'follow_request'
      AND read_at IS NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.respond_follow_request(requester_profile UUID, approve BOOLEAN)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF approve THEN
        UPDATE public.follows
        SET status = 'accepted', responded_at = timezone('utc'::text, now())
        WHERE follower_id = requester_profile
          AND following_id = auth.uid()
          AND status = 'pending';
    ELSE
        DELETE FROM public.follows
        WHERE follower_id = requester_profile
          AND following_id = auth.uid()
          AND status = 'pending';
    END IF;

    UPDATE public.notifications
    SET read_at = COALESCE(read_at, timezone('utc'::text, now()))
    WHERE recipient_id = auth.uid()
      AND actor_id = requester_profile
      AND type = 'follow_request';
END;
$$;

CREATE OR REPLACE FUNCTION public.block_profile(target_profile UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    blocker UUID := auth.uid();
BEGIN
    IF blocker IS NULL OR blocker = target_profile THEN
        RAISE EXCEPTION 'Invalid block target';
    END IF;

    INSERT INTO public.blocks (blocker_id, blocked_id)
    VALUES (blocker, target_profile)
    ON CONFLICT DO NOTHING;

    DELETE FROM public.follows
    WHERE (follower_id = blocker AND following_id = target_profile)
       OR (follower_id = target_profile AND following_id = blocker);

    DELETE FROM public.notifications
    WHERE (recipient_id = blocker AND actor_id = target_profile)
       OR (recipient_id = target_profile AND actor_id = blocker);
END;
$$;

CREATE OR REPLACE FUNCTION public.unblock_profile(target_profile UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    DELETE FROM public.blocks
    WHERE blocker_id = auth.uid() AND blocked_id = target_profile;
END;
$$;

REVOKE ALL ON FUNCTION public.is_blocked_between(UUID, UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.can_view_profile_content(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.update_follow_counts() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.create_follow_notification() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.create_reaction_notification() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.request_follow(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.unfollow_profile(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.respond_follow_request(UUID, BOOLEAN) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.block_profile(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.unblock_profile(UUID) FROM PUBLIC;

GRANT SELECT ON public.follows TO authenticated;
GRANT SELECT ON public.blocks TO authenticated;
GRANT SELECT, INSERT, DELETE ON public.post_reactions TO authenticated;
GRANT SELECT, UPDATE ON public.notifications TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.notifications_id_seq TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_blocked_between(UUID, UUID) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.can_view_profile_content(UUID) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.request_follow(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.unfollow_profile(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.respond_follow_request(UUID, BOOLEAN) TO authenticated;
GRANT EXECUTE ON FUNCTION public.block_profile(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.unblock_profile(UUID) TO authenticated;
