-- Typed reactions, post reporting and administrator moderation.

ALTER TABLE public.post_reactions
    ADD COLUMN IF NOT EXISTS reaction_type TEXT NOT NULL DEFAULT 'like';

ALTER TABLE public.post_reactions
    DROP CONSTRAINT IF EXISTS post_reactions_reaction_type_check;
ALTER TABLE public.post_reactions
    ADD CONSTRAINT post_reactions_reaction_type_check
    CHECK (reaction_type IN ('like', 'love', 'sad'));

ALTER TABLE public.profiles
    ADD COLUMN IF NOT EXISTS is_suspended BOOLEAN NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS public.app_admins (
    profile_id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.account_suspensions (
    profile_id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
    reason TEXT,
    suspended_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    suspended_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.moderation_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    reported_profile_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    post_id UUID REFERENCES public.posts(id) ON DELETE SET NULL,
    category TEXT NOT NULL CHECK (
        category IN ('spam', 'harassment', 'bullying', 'offensive', 'other')
    ),
    details TEXT CHECK (details IS NULL OR char_length(details) <= 1000),
    post_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'resolved')),
    resolution TEXT,
    resolved_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    resolved_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS moderation_reports_open_unique
    ON public.moderation_reports (reporter_id, post_id)
    WHERE status = 'open' AND post_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS moderation_reports_status_created_idx
    ON public.moderation_reports (status, created_at DESC);
CREATE INDEX IF NOT EXISTS moderation_reports_profile_idx
    ON public.moderation_reports (reported_profile_id, created_at DESC);

ALTER TABLE public.app_admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.account_suspensions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.moderation_reports ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.is_current_user_admin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1 FROM public.app_admins WHERE profile_id = auth.uid()
    );
$$;

CREATE OR REPLACE FUNCTION public.is_profile_active(profile UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT CASE
        WHEN profile IS NULL THEN true
        ELSE COALESCE((
            SELECT NOT is_suspended FROM public.profiles WHERE id = profile
        ), false)
    END;
$$;

CREATE OR REPLACE FUNCTION public.can_view_profile_content(owner_profile UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.profiles AS owner
        WHERE owner.id = owner_profile
          AND owner.is_suspended = false
          AND public.is_profile_active(auth.uid())
          AND (
              auth.uid() = owner.id
              OR (
                  NOT public.is_blocked_between(auth.uid(), owner.id)
                  AND (
                      owner.is_private = false
                      OR EXISTS (
                          SELECT 1
                          FROM public.follows
                          WHERE follower_id = auth.uid()
                            AND following_id = owner.id
                            AND status = 'accepted'
                      )
                  )
              )
          )
    );
$$;

DROP POLICY IF EXISTS "Users can add their own reactions" ON public.post_reactions;
CREATE POLICY "Users can add their own reactions"
    ON public.post_reactions FOR INSERT TO authenticated
    WITH CHECK (
        auth.uid() = profile_id
        AND public.is_profile_active(auth.uid())
        AND EXISTS (
            SELECT 1
            FROM public.posts
            WHERE posts.id = post_reactions.post_id
              AND posts.profile_id <> auth.uid()
              AND public.can_view_profile_content(posts.profile_id)
        )
    );

DROP POLICY IF EXISTS "Users can update their own reactions" ON public.post_reactions;
CREATE POLICY "Users can update their own reactions"
    ON public.post_reactions FOR UPDATE TO authenticated
    USING (auth.uid() = profile_id AND public.is_profile_active(auth.uid()))
    WITH CHECK (
        auth.uid() = profile_id
        AND public.is_profile_active(auth.uid())
        AND EXISTS (
            SELECT 1
            FROM public.posts
            WHERE posts.id = post_reactions.post_id
              AND posts.profile_id <> auth.uid()
              AND public.can_view_profile_content(posts.profile_id)
        )
    );

DROP POLICY IF EXISTS "Users can remove their own reactions" ON public.post_reactions;
CREATE POLICY "Users can remove their own reactions"
    ON public.post_reactions FOR DELETE TO authenticated
    USING (auth.uid() = profile_id AND public.is_profile_active(auth.uid()));

DROP POLICY IF EXISTS "Allow authenticated users to insert posts" ON public.posts;
CREATE POLICY "Allow authenticated users to insert posts"
    ON public.posts FOR INSERT TO authenticated
    WITH CHECK (auth.uid() = profile_id AND public.is_profile_active(auth.uid()));

DROP POLICY IF EXISTS "Allow users to update their own profile" ON public.profiles;
CREATE POLICY "Allow users to update their own profile"
    ON public.profiles FOR UPDATE TO authenticated
    USING (auth.uid() = id AND public.is_profile_active(auth.uid()))
    WITH CHECK (auth.uid() = id AND public.is_profile_active(auth.uid()));

DROP POLICY IF EXISTS "Allow authenticated users to insert/delete favorites" ON public.favorites;
CREATE POLICY "Allow authenticated users to insert/delete favorites"
    ON public.favorites FOR ALL TO authenticated
    USING (auth.uid() = profile_id AND public.is_profile_active(auth.uid()))
    WITH CHECK (auth.uid() = profile_id AND public.is_profile_active(auth.uid()));

DROP POLICY IF EXISTS "Allow authenticated users to insert/delete collections" ON public.collections;
CREATE POLICY "Allow authenticated users to insert/delete collections"
    ON public.collections FOR ALL TO authenticated
    USING (auth.uid() = profile_id AND public.is_profile_active(auth.uid()))
    WITH CHECK (auth.uid() = profile_id AND public.is_profile_active(auth.uid()));

DROP POLICY IF EXISTS "Administrators can read reports" ON public.moderation_reports;
CREATE POLICY "Administrators can read reports"
    ON public.moderation_reports FOR SELECT TO authenticated
    USING (public.is_current_user_admin());

DROP POLICY IF EXISTS "Users and administrators can read suspensions" ON public.account_suspensions;
CREATE POLICY "Users and administrators can read suspensions"
    ON public.account_suspensions FOR SELECT TO authenticated
    USING (auth.uid() = profile_id OR public.is_current_user_admin());

CREATE OR REPLACE FUNCTION public.request_follow(target_profile UUID)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    requester UUID := auth.uid();
    target_is_private BOOLEAN;
    existing_status TEXT;
    next_status TEXT;
BEGIN
    IF requester IS NULL OR NOT public.is_profile_active(requester) THEN
        RAISE EXCEPTION 'Account is not active';
    END IF;
    IF requester = target_profile THEN
        RAISE EXCEPTION 'Cannot follow yourself';
    END IF;
    IF NOT public.is_profile_active(target_profile) THEN
        RAISE EXCEPTION 'Profile is not available';
    END IF;
    IF public.is_blocked_between(requester, target_profile) THEN
        RAISE EXCEPTION 'Follow is not available';
    END IF;

    SELECT is_private INTO target_is_private
    FROM public.profiles
    WHERE id = target_profile;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Profile not found';
    END IF;

    SELECT status INTO existing_status
    FROM public.follows
    WHERE follower_id = requester AND following_id = target_profile;
    IF existing_status IS NOT NULL THEN
        RETURN existing_status;
    END IF;

    next_status := CASE WHEN target_is_private THEN 'pending' ELSE 'accepted' END;
    INSERT INTO public.follows (follower_id, following_id, status, responded_at)
    VALUES (
        requester,
        target_profile,
        next_status,
        CASE WHEN next_status = 'accepted' THEN timezone('utc'::text, now()) ELSE NULL END
    );
    RETURN next_status;
END;
$$;

CREATE OR REPLACE FUNCTION public.submit_post_report(
    target_post UUID,
    report_category TEXT,
    report_details TEXT DEFAULT NULL
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    reporter UUID := auth.uid();
    target_row public.posts%ROWTYPE;
    existing_id BIGINT;
    created_id BIGINT;
BEGIN
    IF reporter IS NULL OR NOT public.is_profile_active(reporter) THEN
        RAISE EXCEPTION 'Account is not active';
    END IF;
    IF report_category NOT IN ('spam', 'harassment', 'bullying', 'offensive', 'other') THEN
        RAISE EXCEPTION 'Invalid report category';
    END IF;
    IF report_details IS NOT NULL AND char_length(report_details) > 1000 THEN
        RAISE EXCEPTION 'Report details are too long';
    END IF;

    SELECT * INTO target_row FROM public.posts WHERE id = target_post;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Post not found';
    END IF;
    IF target_row.profile_id = reporter THEN
        RAISE EXCEPTION 'Cannot report your own post';
    END IF;

    SELECT id INTO existing_id
    FROM public.moderation_reports
    WHERE reporter_id = reporter AND post_id = target_post AND status = 'open';
    IF existing_id IS NOT NULL THEN
        RETURN existing_id;
    END IF;

    INSERT INTO public.moderation_reports (
        reporter_id,
        reported_profile_id,
        post_id,
        category,
        details,
        post_snapshot
    ) VALUES (
        reporter,
        target_row.profile_id,
        target_row.id,
        report_category,
        NULLIF(btrim(report_details), ''),
        jsonb_build_object(
            'post_id', target_row.id,
            'profile_id', target_row.profile_id,
            'book_id', target_row.book_id,
            'rating', target_row.rating,
            'review', target_row.comment,
            'created_at', target_row.created_at
        )
    ) RETURNING id INTO created_id;

    RETURN created_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.unfollow_profile(target_profile UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF NOT public.is_profile_active(auth.uid()) THEN
        RAISE EXCEPTION 'Account is not active';
    END IF;
    DELETE FROM public.follows
    WHERE follower_id = auth.uid() AND following_id = target_profile;
    DELETE FROM public.notifications
    WHERE recipient_id = target_profile
      AND actor_id = auth.uid()
      AND type = 'follow_request'
      AND read_at IS NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.respond_follow_request(requester_profile UUID, approve BOOLEAN)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF NOT public.is_profile_active(auth.uid()) THEN
        RAISE EXCEPTION 'Account is not active';
    END IF;
    IF approve AND NOT public.is_profile_active(requester_profile) THEN
        RAISE EXCEPTION 'Profile is not available';
    END IF;
    IF approve THEN
        UPDATE public.follows
        SET status = 'accepted', responded_at = timezone('utc'::text, now())
        WHERE follower_id = requester_profile
          AND following_id = auth.uid()
          AND status = 'pending';
    ELSE
        DELETE FROM public.follows
        WHERE follower_id = requester_profile
          AND following_id = auth.uid()
          AND status = 'pending';
    END IF;
    UPDATE public.notifications
    SET read_at = COALESCE(read_at, timezone('utc'::text, now()))
    WHERE recipient_id = auth.uid()
      AND actor_id = requester_profile
      AND type = 'follow_request';
END;
$$;

CREATE OR REPLACE FUNCTION public.block_profile(target_profile UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    blocker UUID := auth.uid();
BEGIN
    IF NOT public.is_profile_active(blocker) THEN
        RAISE EXCEPTION 'Account is not active';
    END IF;
    IF blocker = target_profile THEN
        RAISE EXCEPTION 'Invalid block target';
    END IF;
    INSERT INTO public.blocks (blocker_id, blocked_id)
    VALUES (blocker, target_profile)
    ON CONFLICT DO NOTHING;
    DELETE FROM public.follows
    WHERE (follower_id = blocker AND following_id = target_profile)
       OR (follower_id = target_profile AND following_id = blocker);
    DELETE FROM public.notifications
    WHERE (recipient_id = blocker AND actor_id = target_profile)
       OR (recipient_id = target_profile AND actor_id = blocker);
END;
$$;

CREATE OR REPLACE FUNCTION public.unblock_profile(target_profile UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF NOT public.is_profile_active(auth.uid()) THEN
        RAISE EXCEPTION 'Account is not active';
    END IF;
    DELETE FROM public.blocks
    WHERE blocker_id = auth.uid() AND blocked_id = target_profile;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_resolve_report(
    target_report BIGINT,
    resolution_note TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF NOT public.is_current_user_admin() THEN
        RAISE EXCEPTION 'Administrator access required';
    END IF;
    UPDATE public.moderation_reports
    SET status = 'resolved',
        resolution = NULLIF(btrim(resolution_note), ''),
        resolved_by = auth.uid(),
        resolved_at = timezone('utc'::text, now())
    WHERE id = target_report;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_delete_reported_post(target_report BIGINT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    target_post UUID;
BEGIN
    IF NOT public.is_current_user_admin() THEN
        RAISE EXCEPTION 'Administrator access required';
    END IF;

    SELECT post_id INTO target_post
    FROM public.moderation_reports
    WHERE id = target_report;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Report not found';
    END IF;

    UPDATE public.moderation_reports
    SET status = 'resolved',
        resolution = 'post_deleted',
        resolved_by = auth.uid(),
        resolved_at = timezone('utc'::text, now())
    WHERE status = 'open'
      AND (id = target_report OR post_id = target_post);

    IF target_post IS NOT NULL THEN
        DELETE FROM public.posts WHERE id = target_post;
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_set_account_suspension(
    target_profile UUID,
    suspend BOOLEAN,
    reason TEXT DEFAULT NULL
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF NOT public.is_current_user_admin() THEN
        RAISE EXCEPTION 'Administrator access required';
    END IF;
    IF target_profile = auth.uid() THEN
        RAISE EXCEPTION 'Cannot suspend your own administrator account';
    END IF;
    IF suspend AND EXISTS (
        SELECT 1 FROM public.app_admins WHERE profile_id = target_profile
    ) THEN
        RAISE EXCEPTION 'Cannot suspend an administrator account';
    END IF;

    UPDATE public.profiles
    SET is_suspended = suspend
    WHERE id = target_profile;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Profile not found';
    END IF;

    IF suspend THEN
        INSERT INTO public.account_suspensions (
            profile_id, reason, suspended_at, suspended_by
        ) VALUES (
            target_profile,
            NULLIF(btrim(reason), ''),
            timezone('utc'::text, now()),
            auth.uid()
        )
        ON CONFLICT (profile_id) DO UPDATE
        SET reason = EXCLUDED.reason,
            suspended_at = EXCLUDED.suspended_at,
            suspended_by = EXCLUDED.suspended_by;
        DELETE FROM public.follows
        WHERE follower_id = target_profile OR following_id = target_profile;
        DELETE FROM public.post_reactions WHERE profile_id = target_profile;
    ELSE
        DELETE FROM public.account_suspensions WHERE profile_id = target_profile;
    END IF;
END;
$$;

-- Users may edit public profile fields, but cannot clear their own suspension.
REVOKE UPDATE ON public.profiles FROM authenticated;
GRANT UPDATE (username, user_id, avatar_url, bio, is_private)
    ON public.profiles TO authenticated;

REVOKE ALL ON FUNCTION public.is_current_user_admin() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.is_profile_active(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.submit_post_report(UUID, TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_resolve_report(BIGINT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_delete_reported_post(BIGINT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_set_account_suspension(UUID, BOOLEAN, TEXT) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.is_current_user_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_profile_active(UUID) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.submit_post_report(UUID, TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_resolve_report(BIGINT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_delete_reported_post(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_account_suspension(UUID, BOOLEAN, TEXT) TO authenticated;
GRANT SELECT ON public.moderation_reports TO authenticated;
GRANT SELECT ON public.account_suspensions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.post_reactions TO authenticated;

COMMENT ON TABLE public.app_admins IS
    'Server-protected allowlist of profiles permitted to moderate Sharemarium.';
COMMENT ON TABLE public.moderation_reports IS
    'Post reports visible only to allowlisted administrators.';
COMMENT ON TABLE public.account_suspensions IS
    'Private suspension reasons visible only to the affected user and administrators.';
