-- Record the exact legal-document versions accepted by each authenticated user.
CREATE TABLE IF NOT EXISTS public.legal_consents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    bundle_version TEXT NOT NULL,
    terms_version TEXT NOT NULL,
    privacy_version TEXT NOT NULL,
    community_guidelines_version TEXT NOT NULL,
    infringement_policy_version TEXT NOT NULL,
    external_transmission_version TEXT NOT NULL,
    auth_provider TEXT,
    accepted_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE (profile_id, bundle_version)
);

ALTER TABLE public.legal_consents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read their own legal consents"
    ON public.legal_consents FOR SELECT
    USING (auth.uid() = profile_id);

CREATE POLICY "Users can insert their own legal consents"
    ON public.legal_consents FOR INSERT
    WITH CHECK (auth.uid() = profile_id);

GRANT SELECT, INSERT ON public.legal_consents TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.legal_consents_id_seq TO authenticated;

-- Contact requests can be submitted before or after login, but are not publicly readable.
CREATE TABLE IF NOT EXISTS public.contact_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    email TEXT NOT NULL CHECK (char_length(email) BETWEEN 3 AND 320),
    category TEXT NOT NULL CHECK (
        category IN ('general', 'privacy', 'infringement', 'report', 'account', 'other')
    ),
    subject TEXT NOT NULL CHECK (char_length(subject) BETWEEN 1 AND 120),
    message TEXT NOT NULL CHECK (char_length(message) BETWEEN 1 AND 4000),
    status TEXT NOT NULL DEFAULT 'received' CHECK (status IN ('received', 'in_progress', 'closed')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.contact_requests ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can submit a contact request"
    ON public.contact_requests FOR INSERT
    TO anon, authenticated
    WITH CHECK (
        status = 'received'
        AND (profile_id IS NULL OR auth.uid() = profile_id)
    );

GRANT INSERT ON public.contact_requests TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.contact_requests_id_seq TO anon, authenticated;

-- Replace only usernames that still expose the local part of an auth email.
UPDATE public.profiles AS profile
SET username = 'reader_' || left(replace(profile.id::text, '-', ''), 10)
FROM auth.users AS auth_user
WHERE profile.id = auth_user.id
  AND auth_user.email IS NOT NULL
  AND lower(profile.username) = lower(split_part(auth_user.email, '@', 1));

-- Future authenticated profiles are tied to auth.users. Existing seed rows are
-- intentionally left unvalidated, while all new rows are checked.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'profiles_auth_user_fkey'
          AND conrelid = 'public.profiles'::regclass
    ) THEN
        ALTER TABLE public.profiles
            ADD CONSTRAINT profiles_auth_user_fkey
            FOREIGN KEY (id) REFERENCES auth.users(id)
            ON DELETE CASCADE NOT VALID;
    END IF;
END $$;
