-- Timeline post replies only (no direct messages).

CREATE TABLE IF NOT EXISTS public.post_replies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id UUID NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
    profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
    CONSTRAINT post_replies_message_length_check
        CHECK (char_length(btrim(message)) BETWEEN 1 AND 100),
    CONSTRAINT post_replies_message_no_url_check
        CHECK (message !~* '(https?://|www\.)'),
    CONSTRAINT post_replies_message_no_media_check
        CHECK (
            message !~* '(<\\s*(img|video|source)\\b|!\\[[^\\]]*\\]\\([^\\)]*\\)|\\.(png|jpe?g|gif|webp|bmp|svg|mp4|mov|avi|wmv|webm|mkv)\\b)'
        ),
    CONSTRAINT post_replies_message_no_phone_check
        CHECK (message !~* '(\\+?\\d[\\d\\s\\-()]{8,}\\d)'),
    CONSTRAINT post_replies_message_no_address_check
        CHECK (message !~* '([0-9０-９]{1,4}(丁目|番地|番|号)|都道府県|都|道|府|県|市|区|町|村)')
);

CREATE INDEX IF NOT EXISTS post_replies_post_created_idx
    ON public.post_replies (post_id, created_at ASC);

ALTER TABLE public.post_replies ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can read post replies" ON public.post_replies;
CREATE POLICY "Public can read post replies"
    ON public.post_replies FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.posts
            WHERE posts.id = post_replies.post_id
        )
    );

DROP POLICY IF EXISTS "Authenticated users can add replies" ON public.post_replies;
CREATE POLICY "Authenticated users can add replies"
    ON public.post_replies FOR INSERT TO authenticated
    WITH CHECK (
        auth.uid() = profile_id
        AND EXISTS (
            SELECT 1 FROM public.posts
            WHERE posts.id = post_replies.post_id
        )
    );

DROP POLICY IF EXISTS "Users can delete own replies" ON public.post_replies;
CREATE POLICY "Users can delete own replies"
    ON public.post_replies FOR DELETE TO authenticated
    USING (auth.uid() = profile_id);

GRANT SELECT, INSERT, DELETE ON public.post_replies TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.post_replies_id_seq TO authenticated;

COMMENT ON TABLE public.post_replies IS
    'Replies for timeline posts only. Direct messages are intentionally unsupported.';